#!/bin/bash
#
#  Run GUI program
#
dir=`dirname $0`
unm=`uname -m`
$dir/loadmod.sh
export CLASSPATH=$0.jar
export Z11RLEXE=$dir/z11rl
export LD_LIBRARY_PATH=$dir
exec java -Dccode=$dir -Dunamem=$unm GUI "$@"
