#!/bin/bash
#
#  Run Z11GUI program
#
dir=`dirname $0`
dir=`realpath $dir`
unm=`uname -m`
$dir/loadmod.sh
export CLASSPATH=$dir/Z11GUI.jar
export Z11HOME=$dir
export LD_LIBRARY_PATH=$dir
dbg=
if [ "$1" == "-gdb" ]
then
    dbg='gdb --args'
    shift
fi
exec $dbg java -Dccode=$dir -Dunamem=$unm Z11GUI "$@"
