#!/bin/bash
#
#  Start z11xe on the zturn board
#
dd=`dirname $0`
$dd/loadmod.sh
dbg=
if [ "$1" == "-gdb" ]
then
    dbg='gdb --args'
    shift
fi
exec sudo --preserve-env=z11xe_debug $dbg $0.`uname -m` -uid $UID -gid "$GROUPS" "$@"
